### ISSUE TITLE
Register New User Doesn't Work For Me

### ISSUE THREAD

**Issue by bisonbrah** [kevinvess/wp-force-login#5] opened 2015-06-03 14:24 UTC
With the plugin installed - once forced to login; users that need to register for access get looped back to the login screen. Any ideas why?

**Comment by kevinvess** [comment] 2015-06-03 15:26
Can you elaborate on your issue some more?

First, is your WordPress install configured to "allow anyone to register"? If so, you should see the link "Register" below the login box.

If you click the "Register" link, it should load the registration page (/wp-login.php?action=register) which allows you to create a username and enter your email address to register as a new user. Then the new user should receive an email from your site with a link to complete the registration process.

At what point in this process are you having trouble? Can you access the registration page?

Also, do you have any other plugins installed? Have you tried deactivating all other plugins to confirm another plugin isn't causing this issue for you?

**Comment by bisonbrah** [comment] 2015-06-03 15:39
Hi Kevin,

Thanks for the speedy response. When I click ‘Lost your password’ it open password reset page; but, when I click ‘Register’ it loops back to the default login page.

Made the following modifications @ functions.php

/**
* Filter Force Login to allow exceptions for specific URLs.
*
* @return array An array of URLs. Must be absolute.
**/
function my_forcelogin_whitelist() {
  return array(
    site_url( '/wp-login.php?action=register/' ),
    site_url( '/wp-login.php?action=lostpassword/' )
  );
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);

Evan Henry
President

**Comment by kevinvess** [comment] 2015-06-03 15:55
There must be something unique to your WordPress site that is causing this issue.

Try following these steps to determine the cause of your issue:
https://wordpress.org/support/topic/infinite-loop-5#post-5933211

Also, you shouldn't need to add exceptions for those URLs because they're already exempt from the force login and if you already can't access those URLs – adding an additional exception probably won't fix it.

However, with that said, you should remove the trailing slash from your code:

```php
/**
* Filter Force Login to allow exceptions for specific URLs.
*
* @return array An array of URLs. Must be absolute.
**/
function my_forcelogin_whitelist() {
  return array(
    site_url( '/wp-login.php?action=register' ),
    site_url( '/wp-login.php?action=lostpassword' )
  );
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```

**Comment by bisonbrah** [comment] 2015-06-03 15:59
NOTED @ trailing slashes & I’ll reference the link provided.

Only thing is; when your plugin is not active my end users can register just fine..

Evan Henry
President

**Comment by kevinvess** [comment] 2015-06-03 21:09
Well sure, your users can register "just fine" when the plugin is deactivated, but that does not necessarily mean *Force Login* is causing your issue. When the plugin is deactivated, it's not trying to redirect visitors anywhere and thus you have no issue with registration being "looped back."

For example, your theme or another plugin could have changed the registration URL from the standard WordPress URL to something else – which, *Force Login* is only allowing the standard URL and wouldn't recognize this new registration URL and thus redirects visitors back to the login screen.

What is the URL for your registration page? Can you double checked this?

The plugin allows visitors to see the `/wp-login.php` page URL, with any query string(s), but if your site is using a different page URL to handle the registration page then you will need to make an exception for that URL using the `my_forcelogin_whitelist` code you shared before.

**Comment by bisonbrah** [comment] 2015-06-08 19:34
Sorry for the delayed response I was on vacation.

Registration URL  is https://rhinoleadershipteam.com/register

This should be getting added to the child theme correct?

Evan Henry
President

**Comment by kevinvess** [comment] 2015-06-08 20:27
Thanks for sharing your registration URL with me, this clears things up a bit.

You're not using the standard WordPress registration URL `/wp-login.php?action=register`; I assume you've accomplished this by using another plugin or the option came built-in with your theme. Either way, your issue is that *Force Login* had no way of knowing how to whitelist your unique registration URL(s) by default.

Additionally, it looks like your site redirects visitors to the standard registration URL over to your unique one (which is not recognized by *Force Login*) and gets sent back to the login screen  – which is why clicking on the "Register" link on the login screen did not work.

Try adding the following code to your theme or child-theme's functions.php file:

```php
/**
* Filter Force Login to allow exceptions for specific URLs.
*
* @return array An array of URLs. Must be absolute.
**/
function my_forcelogin_whitelist() {
  return array(
    site_url( '/register' )
  );
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);
```

Keep in mind, there may be additional URLs that need to be whitelisted before your registration process is completely accessible; given that I don't know how you've configured your unique registration process – I can't say for sure what all need to be whitelisted.

**Closed by kevinvess** 2015-06-08 20:27 UTC
